In [1]:
%pylab qt5
%matplotlib

Populating the interactive namespace from numpy and matplotlib
Using matplotlib backend: Qt5Agg


/home/ca/.local/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['fabs', 'modf', 'log10', 'hypot', 'isnan', 'copysign', 'log2', 'exp', 'ldexp', 'cosh', 'isfinite', 'nan', 'log1p', 'fmod', 'gamma', 'log', 'e', 'cos', 'trunc', 'radians', 'sqrt', 'ceil', 'floor', 'expm1', 'pi', 'tanh', 'degrees', 'inf', 'tan', 'frexp', 'isinf', 'sinh', 'isclose', 'sin']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


### Kupfer

In [30]:
Cu1 = [767 - 35, 1612 - 84, 2366 - 168, 3154 - 168, 3938 - 172, 4718 - 172]
Cu2 = [2380 - 1900, 2380 - 1130, 2380 - 300, 3220 - 370]
Cu3 = [3590 - 2360, 3590 - 1570, 3590 - 770, 3590 - 20]

In [32]:
diff(Cu1)
diff(Cu2)
diff(Cu3)

array([796, 670, 788, 780, 780])

array([770, 830, 770])

array([790, 800, 750])

In [39]:
plt.plot(zeros(len(Cu1) - 1), diff(Cu1), 'o')
plt.plot(zeros(len(Cu2) - 1), diff(Cu2), 'o')
plt.plot(zeros(len(Cu3) - 1), diff(Cu3), 'o')

### Plastik

In [30]:
P1 = [767 - 35, 1612 - 84, 2366 - 168, 3154 - 168, 3938 - 172, 4718 - 172]
P2 = [2380 - 1900, 2380 - 1130, 2380 - 300, 3220 - 370]
P3 = [3590 - 2360, 3590 - 1570, 3590 - 770, 3590 - 20]

In [32]:
diff(Cu1)
diff(Cu2)
diff(Cu3)

array([796, 670, 788, 780, 780])

array([770, 830, 770])

array([790, 800, 750])

In [39]:
plt.plot(zeros(len(Cu1) - 1), diff(Cu1), 'o')
plt.plot(zeros(len(Cu2) - 1), diff(Cu2), 'o')
plt.plot(zeros(len(Cu3) - 1), diff(Cu3), 'o')